from absolute_value_tests import *
from add_tests import *
from add_unit_tests import *
from decrementation_tests import *
from incrementation_tests import *
from multiplication_tests import *
from multiplication_by_unit_tests import *
from negation_tests import *
from sign_multiplication_tests import *
from sub_tests import *
from sub_unit_tests import *
