from nand_test import *
from and_test import *
from nor_test import *
from not_test import *
from or_test import *
from xor_test import *
from rotate_left_test import *
from rotate_right_test import *
from shift_left_test import *
from shift_right_test import *